# Sample YAML configuration file.
# Copy to config.yaml or config.yml in the project root and adjust settings as needed.
# config.yaml example
# Base directory for training data and model outputs (default: ./data)
dataDir: './data'
# Base directory for budget data (downloaded budget files; default: ./data/budget)
budgetDir: './data/budget'
# Classification schedule (once an hour on the hour)
CLASSIFY_CRON: '0 * * * *'
CLASSIFY_CRON_TIMEZONE: UTC
# Training schedule (once a week Monday at 06:30 UTC)
TRAIN_CRON: '30 6 * * 1'
TRAIN_CRON_TIMEZONE: UTC
# Disable cron scheduling (daemon mode only; default: false)
DISABLE_CRON_SCHEDULING: false
# Logging level (info, debug, error)
LOG_LEVEL: info
# Classifier to use: 'ml' for Embed+KNN or 'tf' for TensorFlow.js (default: ml)
CLASSIFIER_TYPE: ml
